server:
  port: 8080
spring:
  application:
    name: client
  cloud:
    nacos:
      server-addr: localhost:8848
#      config: #配置无效
#        file-extension: yaml
#        prefix: testConfig
  profiles:
    active: dev
provider:
  testUrl: http://provider

feign:
  hystrix:
    enabled: true # 只对feign有效

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
